DROP TABLE IF EXISTS PRICES;

CREATE TABLE PRICES (
    ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
    BRAND_ID    BIGINT         NOT NULL,
    START_DATE  TIMESTAMP      NOT NULL,
    END_DATE    TIMESTAMP      NOT NULL,
    PRICE_LIST  INT            NOT NULL,
    PRODUCT_ID  BIGINT         NOT NULL,
    PRIORITY    INT            NOT NULL,
    PRICE       DECIMAL(10, 2) NOT NULL,
    CURR        VARCHAR(3)     NOT NULL,
    CONSTRAINT CHK_PRICES_DATES CHECK (END_DATE >= START_DATE)
);

-- Índice que cubre los filtros de la consulta del precio aplicable
CREATE INDEX IDX_PRICES_LOOKUP ON PRICES (BRAND_ID, PRODUCT_ID, START_DATE, END_DATE);
